### ISSUE TITLE
Sliced Meat has no Nutrition

### ISSUE THREAD

**Issue by NotFuji** [Art3m1sVS/sandwichmodVS#4]
Sliced meat has no nutrition

![meatnutrition](https://github.com/user-attachments/assets/104cb861-4497-4a7e-ab58-751725cd2b83)

Mods list:
- A Culinary Artillery
- Alchemy
- Animal Cages
- Blacksmith Enhancements
- Bricklayers
- Carry On
- Chisel Tools
- Coinage
- Common LIb
- Decor Bazaar
- Dressmakers
- Drifters Belong Underground
- Expanded Matter
- Expanded Foods
- FendragonBCS
- Food Shelves
- Medieval Expansion
- Millwright
- Nail Mold
- Not Only Spear Expansion
- One Roof
- Primitive Survival
- Rivers
- Sailboat
- Sammiches
- Shear Lib
- Stone Bake Overn
- Stone Quarry
- Tailors Delight
- Tule Propagation
- Vinconomy
- VS Instruments
- Wild Farming Revival
- Wool

client-main.txt
[client-main.txt](https://github.com/user-attachments/files/17742551/client-main.txt)

**Comment by Art3m1sVS** [comment]
Fixed as of 1.2.5
